name: Branch Cleanup - Dev Merge Protected

on: [push, pull_request_target]

jobs:
  conoleLog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: conole.log
        run: |
          ls -a

  branch_cleanup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Delete branch
        if: github.event.pull_request.merged == 'true'
        run: |
         git push origin --delete ${{ github.event.pull_request.head.ref }}
