name: Branch Cleanup - Dev Merge Protected

on: [push, pull_request_target]

jobs:
  branch_cleanup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: conole.log
        run: |
          ls -a
          echo "github.event.pull_request.merged           : $MERGED_RAW"
          echo "github.event.pull_request.merged == 'true' : $MERGED_TRUE_STR"
          echo "github.event.pull_request.merged  == true  : $MERGED_TRUE_BOOL"
      
      - name: Delete branch
        if: github.event.pull_request.merged == 'true'
        run: |
         git push origin --delete ${{ github.event.pull_request.head.ref }}

    env:
        MERGED_RAW: ${{ github.event.pull_request.merged }}
        MERGED_TRUE_STR: ${{ github.event.pull_request.merged == 'true' }}
        MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}

      
