name: Branch Cleanup - Dev Merge Protected

on: [push, pull_request]

jobs:
  branch_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: conole.log
        run: |
           ls -a

      - name: Delete branch
        if: github.event.pull_request.merged == true
        run: |
         git push origin --delete ${{ github.event.pull_request.head.ref }}
