name: Branch Cleanup - Dev Merge Protected

on:
  pull_request:
    types: [closed, push]

jobs:
  branch_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: conole.log
        run: |
           ls -a

      #- name: Delete branch
      #  run: |
      #    git push origin --delete ${{ github.event.pull_request.head.ref }}
